openapi: 3.0.3
info:
  title: eComTransactionCredentials
  description: eComTransactionCredentials
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  /generate:
    post:
      requestBody:
        description: Generate transaction credentials
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CGR'
        required: true
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Error
          content:
            text/plain:
              schema:
                type: string
  /validate:
    get:
      requestBody:
        description: Validates Transaction Credentials
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CVR'
        required: true
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                enum:
                  - SUCCESS
                  - FAILURE
        '402':
          description: Error
          content:
            text/plain:
              schema:
                type: string
                enum:
                  - REPLAY
components:
  schemas:
    CGR:
      type: object
      properties:
        transaction:
          $ref: '#/components/schemas/Transaction'
        merchant:
          type: string
    CVR:
      type: object
      properties:
        transaction:
          $ref: '#/components/schemas/Transaction'
        transactioncredentials:
          type: string
    Transaction:
      type: object
      properties:
        paymentcardetails:
          $ref: '#/components/schemas/PaymentCardDetails'
        amount:
          type: integer
          format: int32
    PaymentCardDetails:
      type: object
      required:
        - pan
      properties:
        pan:
          type: integer
          format: int64
        expiryDate:
          type: string
          format: date